### ISSUE TITLE
support for 3.3?

### ISSUE THREAD

**Issue by malec** [Devinci297/MSFS-LOD-Maker#2]
Hi, thank you for the addon. Is there no support for blender 3.3? When I install with 3.3, I get a permission error.

If one were to make this compatible with 3.3, what changes would be required?

Thanks

**Comment by Devinci297** [comment]
Hello Malec,
No support for 3.3 is available at this time, the addon works with 3.6 and perhaps newer releases. I tested it to work with 4.2 to some extent. Would you provide the error code perhaps?

The basics of the addon is just Python and it shouldn't be too complicated to adapt it to 3.3.

Regards,
Devinci

**Comment by malec** [comment]
Will try to follow up on this.
