### ISSUE TITLE
"Modifier requires more than 3 input faces"

### ISSUE THREAD

**Issue by malec** [Devinci297/MSFS-LOD-Maker#3]
I have meshes that have one face (to simulate a panel light, with emission), and I'm getting errors:

"LOD_Decimate Modifier requires more than 3 input faces"

Makes sense, but is there any way to exclude certain objects / meshes from being LOD'd?
Ex: if the object has a certain keyword in the name, don't LOD that object, or it's children.

Thanks

**Comment by Devinci297** [comment]
Hello sorry but I just noticed this message.
The error is from Blender itself. Decimate modifiers always needs more than 1 face for it to work because its objective is to reduce the number of faces as much as possible.

Best Regards,

**Comment by Devinci297** [comment]
> Makes sense, but is there any way to exclude certain objects / meshes from being LOD'd? Ex: if the object has a certain keyword in the name, don't LOD that object, or it's children.

For now you have to put those objects in a different collection temporarily. Perhaps in the future I'll add that as an option. Thanks for the suggestion.

Regards,
